spring.application.name=ihpappbackend
defaultUser=defaultuser
environment=local
truststore.location=/opt/keystores/Trust.jks
javax.net.ssl.trustStore=/opt/keystores/Trust.jks
javax.net.ssl.trustStorePassword=password
spring.datasource.username=dittanvändarnamn
spring.datasource.password=dittlösenord
spring.datasource.jdbc-url=jdbc:postgresql://db:5432/ihp
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=ihp
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.url=/v3/api-docs
springdoc.packagesToScan=se.migrationsverket.ihpservice.api.rest.v1
server.forward-headers-strategy=framework
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=startup,prometheus,metrics,info,health,metrics
management.endpoint.health.probes.enabled=true
management.endpoint.health.group.readiness.include=readinessState,db
management.endpoint.health.group.readiness.show-details=always
management.endpoint.prometheus.access=unrestricted
management.endpoint.info.access=unrestricted
management.endpoint.metrics.access=unrestricted
