-- SEQUENCES --

DROP SEQUENCE IF EXISTS assignedrule_id_seq;

CREATE SEQUENCE assignedrule_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS elements_datatype_id_seq;

CREATE SEQUENCE elements_datatype_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS elements_document_id_seq;

CREATE SEQUENCE elements_document_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS elements_id_seq;

CREATE SEQUENCE elements_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS elements_issue_id_seq;

CREATE SEQUENCE elements_issue_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS generic_nod_id_seq;

CREATE SEQUENCE generic_nod_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS history_id_seq;

CREATE SEQUENCE history_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS ihp_established_id_seq;

CREATE SEQUENCE ihp_established_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS ihpservice_seq;

CREATE SEQUENCE ihpservice_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS nodecomment_id_seq;

CREATE SEQUENCE nodecomment_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS noderelation_id_seq;

CREATE SEQUENCE noderelation_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS pdf_id_seq;

CREATE SEQUENCE pdf_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS rule_id_seq;

CREATE SEQUENCE rule_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS snapshot_id_seq;

CREATE SEQUENCE snapshot_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 NO CYCLE;

DROP SEQUENCE IF EXISTS term_id_seq;

CREATE SEQUENCE term_id_seq INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 NO CYCLE;

-- END SEQUENCES --